#!/bin/bash
#
# Convert png files to gif
#
if [ $# -ne 1 ]; then
    echo "usage: `basename $0` <input-dir>"
    exit 1
fi

input_dir=$1
PWD=`pwd`
cd $input_dir
for file in *.tga; do
    base_file=${file%.tga}
    echo "file: $file"
    convert $file ${base_file}.jpg
done

